from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Sequence

@dataclass(frozen=True, slots=True)
class RssSource:
    id: str
    publisher_id: str
    source_en: str
    source_zh: str
    feed_name: str
    feed_url: str
    adapter_id: str
    language: str = 'en'
    region: str = 'global'
    categories: List[str] = field(default_factory=list)
    enabled: bool = True
    priority: int = 50
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

RSS_SOURCE_DATA = [{'id': 'aa:default',
  'publisher_id': 'aa',
  'source_en': 'Anadolu Agency',
  'source_zh': '阿纳多卢通讯社',
  'language': 'tr',
  'region': 'turkey',
  'adapter_id': 'aa',
  'feed_name': 'Default',
  'feed_url': 'https://www.aa.com.tr/tr/rss',
  'categories': ['Default'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:top_stories',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'Top Stories',
  'feed_url': 'https://www.abc.net.au/news/feed/10719986/rss.xml',
  'categories': ['Top Stories'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:world',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'World',
  'feed_url': 'https://www.abc.net.au/news/feed/104217382/rss.xml',
  'categories': ['World'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:business',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'Business',
  'feed_url': 'https://www.abc.net.au/news/feed/104217374/rss.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:politics',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'Politics',
  'feed_url': 'https://www.abc.net.au/news/feed/104217372/rss.xml',
  'categories': ['Politics'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'aljazeera:all',
  'publisher_id': 'aljazeera',
  'source_en': 'Al Jazeera',
  'source_zh': '半岛电视台',
  'language': 'en',
  'region': 'middle_east',
  'adapter_id': 'aljazeera',
  'feed_name': 'All',
  'feed_url': 'https://www.aljazeera.com/xml/rss/all.xml',
  'categories': ['All'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:africa',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Africa',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/africa/rss.xml',
  'categories': ['Africa'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:asia',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Asia',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/asia/rss.xml',
  'categories': ['Asia'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:europe',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Europe',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/europe/rss.xml',
  'categories': ['Europe'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:latin_america',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Latin America',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/latin_america/rss.xml',
  'categories': ['Latin America'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:middle_east',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Middle East',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/middle_east/rss.xml',
  'categories': ['Middle East'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:us_and_canada',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'US & Canada',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml',
  'categories': ['US & Canada'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:england',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'England',
  'feed_url': 'https://feeds.bbci.co.uk/news/england/rss.xml',
  'categories': ['England'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:northern_ireland',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Northern Ireland',
  'feed_url': 'https://feeds.bbci.co.uk/news/northern_ireland/rss.xml',
  'categories': ['Northern Ireland'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:scotland',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Scotland',
  'feed_url': 'https://feeds.bbci.co.uk/news/scotland/rss.xml',
  'categories': ['Scotland'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:wales',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Wales',
  'feed_url': 'https://feeds.bbci.co.uk/news/wales/rss.xml',
  'categories': ['Wales'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:world_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'World News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-world',
  'categories': ['World News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:canada_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'Canada News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-canada',
  'categories': ['Canada News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:business_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'Business News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-business',
  'categories': ['Business News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:technology_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'Technology News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-technology',
  'categories': ['Technology News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:时政新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '时政新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/china.xml',
  'categories': ['时政新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:国际新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '国际新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/world.xml',
  'categories': ['国际新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:财经新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '财经新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/finance.xml',
  'categories': ['财经新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:即时新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '即时新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/scroll-news.xml',
  'categories': ['即时新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:要闻导读',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '要闻导读',
  'feed_url': 'https://www.chinanews.com.cn/rss/importnews.xml',
  'categories': ['要闻导读'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:germany',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Germany',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-ger',
  'categories': ['Germany'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:world',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'World',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-world',
  'categories': ['World'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:europe',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Europe',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-eu',
  'categories': ['Europe'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:africa',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Africa',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-africa',
  'categories': ['Africa'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:business',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Business',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-bus',
  'categories': ['Business'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:science',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Science',
  'feed_url': 'https://rss.dw.com/xml/rss_en_science',
  'categories': ['Science'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:asia',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Asia',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-asia',
  'categories': ['Asia'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:最新消息',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '最新消息',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ultimas-noticias/portada',
  'categories': ['最新消息'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:观看次数最多',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '观看次数最多',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/lo-mas-visto/portada',
  'categories': ['观看次数最多'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:社会',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '社会',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/sociedad/portada',
  'categories': ['社会'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:国际',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '国际',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada',
  'categories': ['国际'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:西班牙',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '西班牙',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/espana/portada',
  'categories': ['西班牙'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:经济',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '经济',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/economia/portada',
  'categories': ['经济'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:科学',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '科学',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada',
  'categories': ['科学'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:商业',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '商业',
  'feed_url': 'https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/economia/subsection/negocios',
  'categories': ['商业'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:analysis',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Analysis',
  'feed_url': 'https://www.investing.com/rss/121899.rss',
  'categories': ['Analysis'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:market_overview',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Market Overview',
  'feed_url': 'https://www.investing.com/rss/market_overview.rss',
  'categories': ['Market Overview'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:swot_analysis_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'SWOT Analysis News',
  'feed_url': 'https://www.investing.com/rss/news_1060.rss',
  'categories': ['SWOT Analysis News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:stock_analyst_ratings',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Stock Analyst Ratings',
  'feed_url': 'https://www.investing.com/rss/news_1061.rss',
  'categories': ['Stock Analyst Ratings'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:cryptocurrency_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Cryptocurrency News',
  'feed_url': 'https://www.investing.com/rss/news_301.rss',
  'categories': ['Cryptocurrency News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:company_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Company News',
  'feed_url': 'https://www.investing.com/rss/news_356.rss',
  'categories': ['Company News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:insider_trading_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Insider Trading News',
  'feed_url': 'https://www.investing.com/rss/news_357.rss',
  'categories': ['Insider Trading News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:forex_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Forex News',
  'feed_url': 'https://www.investing.com/rss/news_1.rss',
  'categories': ['Forex News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:commodities_and_futures_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Commodities & Futures News',
  'feed_url': 'https://www.investing.com/rss/news_11.rss',
  'categories': ['Commodities & Futures News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:stock_market_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Stock Market News',
  'feed_url': 'https://www.investing.com/rss/news_25.rss',
  'categories': ['Stock Market News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:economic_indicators_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Economic Indicators News',
  'feed_url': 'https://www.investing.com/rss/news_95.rss',
  'categories': ['Economic Indicators News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:economy_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Economy News',
  'feed_url': 'https://www.investing.com/rss/news_14.rss',
  'categories': ['Economy News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_1',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 1',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat1.xml',
  'categories': ['Category 1'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_4',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 4',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat4.xml',
  'categories': ['Category 4'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_5',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 5',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat5.xml',
  'categories': ['Category 5'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_6',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 6',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat6.xml',
  'categories': ['Category 6'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'guardian:world',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'World',
  'feed_url': 'https://www.theguardian.com/world/rss',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'guardian:business',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'Business',
  'feed_url': 'https://www.theguardian.com/business/rss',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'guardian:technology',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'Technology',
  'feed_url': 'https://www.theguardian.com/technology/rss',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'guardian:environment',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'Environment',
  'feed_url': 'https://www.theguardian.com/environment/rss',
  'categories': ['Environment'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'nyt:world',
  'publisher_id': 'nyt',
  'source_en': 'The New York Times',
  'source_zh': '纽约时报',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'nyt',
  'feed_name': 'World',
  'feed_url': 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'nyt:business',
  'publisher_id': 'nyt',
  'source_en': 'The New York Times',
  'source_zh': '纽约时报',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'nyt',
  'feed_name': 'Business',
  'feed_url': 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'nyt:technology',
  'publisher_id': 'nyt',
  'source_en': 'The New York Times',
  'source_zh': '纽约时报',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'nyt',
  'feed_name': 'Technology',
  'feed_url': 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'ft:world',
  'publisher_id': 'ft',
  'source_en': 'Financial Times',
  'source_zh': '金融时报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ft',
  'feed_name': 'World',
  'feed_url': 'https://www.ft.com/world?format=rss',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'ft:companies',
  'publisher_id': 'ft',
  'source_en': 'Financial Times',
  'source_zh': '金融时报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ft',
  'feed_name': 'Companies',
  'feed_url': 'https://www.ft.com/companies?format=rss',
  'categories': ['Companies'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'ft:technology',
  'publisher_id': 'ft',
  'source_en': 'Financial Times',
  'source_zh': '金融时报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ft',
  'feed_name': 'Technology',
  'feed_url': 'https://www.ft.com/technology?format=rss',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'npr:world',
  'publisher_id': 'npr',
  'source_en': 'NPR',
  'source_zh': '美国国家公共电台',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'npr',
  'feed_name': 'World',
  'feed_url': 'https://feeds.npr.org/1004/rss.xml',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'npr:business',
  'publisher_id': 'npr',
  'source_en': 'NPR',
  'source_zh': '美国国家公共电台',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'npr',
  'feed_name': 'Business',
  'feed_url': 'https://feeds.npr.org/1006/rss.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'npr:technology',
  'publisher_id': 'npr',
  'source_en': 'NPR',
  'source_zh': '美国国家公共电台',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'npr',
  'feed_name': 'Technology',
  'feed_url': 'https://feeds.npr.org/1019/rss.xml',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'politico:politics',
  'publisher_id': 'politico',
  'source_en': 'Politico',
  'source_zh': '政客',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'politico',
  'feed_name': 'Politics',
  'feed_url': 'https://rss.politico.com/politics-news.xml',
  'categories': ['Politics'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'techcrunch:startup_and_tech',
  'publisher_id': 'techcrunch',
  'source_en': 'TechCrunch',
  'source_zh': 'TechCrunch',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'techcrunch',
  'feed_name': 'Main Feed',
  'feed_url': 'https://techcrunch.com/feed/',
  'categories': ['Technology', 'Startups'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'cnbc:world',
  'publisher_id': 'cnbc',
  'source_en': 'CNBC',
  'source_zh': '美国消费者新闻与商业频道',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'cnbc',
  'feed_name': 'World',
  'feed_url': 'https://www.cnbc.com/id/100727362/device/rss/rss.html',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'cnbc:business',
  'publisher_id': 'cnbc',
  'source_en': 'CNBC',
  'source_zh': '美国消费者新闻与商业频道',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'cnbc',
  'feed_name': 'Business',
  'feed_url': 'https://www.cnbc.com/id/10001147/device/rss/rss.html',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'marketwatch:topstories',
  'publisher_id': 'marketwatch',
  'source_en': 'MarketWatch',
  'source_zh': '道琼斯市场观察',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'marketwatch',
  'feed_name': 'Top Stories',
  'feed_url': 'https://feeds.content.dowjones.io/public/rss/mw_topstories',
  'categories': ['Markets', 'Top Stories'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'economist:international',
  'publisher_id': 'economist',
  'source_en': 'The Economist',
  'source_zh': '经济学人',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'economist',
  'feed_name': 'International',
  'feed_url': 'https://www.economist.com/international/rss.xml',
  'categories': ['International'],
  'enabled': False,
  'priority': 60,
  'metadata': {'disabled_reason': 'article_pages_return_403',
               'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'economist:business',
  'publisher_id': 'economist',
  'source_en': 'The Economist',
  'source_zh': '经济学人',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'economist',
  'feed_name': 'Business',
  'feed_url': 'https://www.economist.com/business/rss.xml',
  'categories': ['Business'],
  'enabled': False,
  'priority': 60,
  'metadata': {'disabled_reason': 'article_pages_return_403',
               'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'economist:finance',
  'publisher_id': 'economist',
  'source_en': 'The Economist',
  'source_zh': '经济学人',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'economist',
  'feed_name': 'Finance and Economics',
  'feed_url': 'https://www.economist.com/finance-and-economics/rss.xml',
  'categories': ['Finance', 'Economics'],
  'enabled': False,
  'priority': 60,
  'metadata': {'disabled_reason': 'article_pages_return_403',
               'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'un_news:all',
  'publisher_id': 'un_news',
  'source_en': 'UN News',
  'source_zh': '联合国新闻',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'un_news',
  'feed_name': 'All News',
  'feed_url': 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
  'categories': ['World', 'Policy'],
  'enabled': True,
  'priority': 62,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'mit_tech_review:main',
  'publisher_id': 'mit_tech_review',
  'source_en': 'MIT Technology Review',
  'source_zh': '麻省理工科技评论',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'mit_tech_review',
  'feed_name': 'Main',
  'feed_url': 'https://www.technologyreview.com/feed/',
  'categories': ['Technology', 'AI'],
  'enabled': True,
  'priority': 61,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'ars:main',
  'publisher_id': 'ars',
  'source_en': 'Ars Technica',
  'source_zh': 'Ars Technica',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ars',
  'feed_name': 'Main',
  'feed_url': 'https://feeds.arstechnica.com/arstechnica/index',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 61,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'register:headlines',
  'publisher_id': 'register',
  'source_en': 'The Register',
  'source_zh': 'The Register',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'register',
  'feed_name': 'Headlines',
  'feed_url': 'https://www.theregister.com/headlines.atom',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'nature:main',
  'publisher_id': 'nature',
  'source_en': 'Nature',
  'source_zh': 'Nature',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'nature',
  'feed_name': 'Main',
  'feed_url': 'https://www.nature.com/nature.rss',
  'categories': ['Science'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'nasa:breaking',
  'publisher_id': 'nasa',
  'source_en': 'NASA',
  'source_zh': '美国国家航空航天局',
  'language': 'en',
  'region': 'us',
  'adapter_id': 'nasa',
  'feed_name': 'Breaking News',
  'feed_url': 'https://www.nasa.gov/rss/dyn/breaking_news.rss',
  'categories': ['Science', 'Space'],
  'enabled': True,
  'priority': 59,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'stat_news:main',
  'publisher_id': 'stat_news',
  'source_en': 'STAT',
  'source_zh': 'STAT',
  'language': 'en',
  'region': 'us',
  'adapter_id': 'stat_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.statnews.com/feed/',
  'categories': ['Health', 'Science'],
  'enabled': True,
  'priority': 59,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'foreign_policy:main',
  'publisher_id': 'foreign_policy',
  'source_en': 'Foreign Policy',
  'source_zh': '外交政策',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'foreign_policy',
  'feed_name': 'Main',
  'feed_url': 'https://foreignpolicy.com/feed/',
  'categories': ['World', 'Politics'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'euronews:news',
  'publisher_id': 'euronews',
  'source_en': 'Euronews',
  'source_zh': '欧洲新闻台',
  'language': 'en',
  'region': 'europe',
  'adapter_id': 'euronews',
  'feed_name': 'News',
  'feed_url': 'https://www.euronews.com/rss?level=theme&name=news',
  'categories': ['World', 'Europe'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'bbc:anyfeeder_top',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Top Stories',
  'feed_url': 'https://plink.anyfeeder.com/bbc',
  'categories': ['Top Stories'],
  'enabled': True,
  'priority': 42,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_world',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'World',
  'feed_url': 'https://plink.anyfeeder.com/bbc/world',
  'categories': ['World'],
  'enabled': True,
  'priority': 42,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_business',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Business',
  'feed_url': 'https://plink.anyfeeder.com/bbc/business',
  'categories': ['Business'],
  'enabled': True,
  'priority': 44,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_politics',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'uk',
  'adapter_id': 'bbc',
  'feed_name': 'Politics',
  'feed_url': 'https://plink.anyfeeder.com/bbc/politics',
  'categories': ['Politics'],
  'enabled': True,
  'priority': 48,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_health',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Health',
  'feed_url': 'https://plink.anyfeeder.com/bbc/health',
  'categories': ['Health'],
  'enabled': True,
  'priority': 48,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_technology',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Technology',
  'feed_url': 'https://plink.anyfeeder.com/bbc/technology',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 48,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_science',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Science & Environment',
  'feed_url': 'https://plink.anyfeeder.com/bbc/science_and_environment',
  'categories': ['Science', 'Environment'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'bbc:anyfeeder_entertainment',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Entertainment & Arts',
  'feed_url': 'https://plink.anyfeeder.com/bbc/entertainment_and_arts',
  'categories': ['Culture'],
  'enabled': True,
  'priority': 55,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'businessinsider:main',
  'publisher_id': 'businessinsider',
  'source_en': 'Business Insider',
  'source_zh': '商业内幕',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://plink.anyfeeder.com/businessinsider',
  'categories': ['Business', 'Technology', 'Markets'],
  'enabled': True,
  'priority': 46,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'time:main',
  'publisher_id': 'time',
  'source_en': 'TIME',
  'source_zh': '时代周刊',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://plink.anyfeeder.com/time',
  'categories': ['World', 'Politics', 'Business'],
  'enabled': True,
  'priority': 48,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'theatlantic:main',
  'publisher_id': 'theatlantic',
  'source_en': 'The Atlantic',
  'source_zh': '大西洋月刊',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://plink.anyfeeder.com/theatlantic',
  'categories': ['Politics', 'World', 'Culture'],
  'enabled': True,
  'priority': 54,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'zerohedge:main',
  'publisher_id': 'zerohedge',
  'source_en': 'ZeroHedge',
  'source_zh': 'ZeroHedge',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://plink.anyfeeder.com/zerohedge',
  'categories': ['Markets', 'Economy'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'vice:main',
  'publisher_id': 'vice',
  'source_en': 'Vice',
  'source_zh': 'Vice',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://plink.anyfeeder.com/vice',
  'categories': ['Culture', 'World'],
  'enabled': True,
  'priority': 62,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'longreads:main',
  'publisher_id': 'longreads',
  'source_en': 'Longreads',
  'source_zh': 'Longreads',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://plink.anyfeeder.com/longreads',
  'categories': ['Longform'],
  'enabled': True,
  'priority': 70,
  'metadata': {'origin': 'feeds-en.opml', 'provider': 'anyfeeder'}},
 {'id': 'daringfireball:main',
  'publisher_id': 'daringfireball',
  'source_en': 'Daring Fireball',
  'source_zh': 'Daring Fireball',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://daringfireball.net/feeds/main',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 68,
  'metadata': {'origin': 'feeds-en.opml'}},
 {'id': 'sixcolors:main',
  'publisher_id': 'sixcolors',
  'source_en': 'Six Colors',
  'source_zh': 'Six Colors',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://feedpress.me/sixcolors',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 68,
  'metadata': {'origin': 'feeds-en.opml'}},
 {'id': 'css_tricks:main',
  'publisher_id': 'css_tricks',
  'source_en': 'CSS-Tricks',
  'source_zh': 'CSS-Tricks',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://css-tricks.com/feed/',
  'categories': ['Technology', 'Web Development'],
  'enabled': True,
  'priority': 72,
  'metadata': {'origin': 'feeds-en.opml'}},
 {'id': 'openai:news',
  'publisher_id': 'openai',
  'source_en': 'OpenAI',
  'source_zh': 'OpenAI',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'News',
  'feed_url': 'https://openai.com/news/rss.xml',
  'categories': ['AI', 'Technology'],
  'enabled': False,
  'priority': 34,
  'metadata': {'disabled_reason': 'article_pages_return_403',
               'origin': 'feeds.opml'}},
 {'id': 'google_ai:main',
  'publisher_id': 'google_ai',
  'source_en': 'Google AI Blog',
  'source_zh': 'Google AI Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'AI Blog',
  'feed_url': 'https://blog.google/technology/ai/rss/',
  'categories': ['AI', 'Technology'],
  'enabled': True,
  'priority': 38,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'arxiv:cs_ai',
  'publisher_id': 'arxiv',
  'source_en': 'arXiv',
  'source_zh': 'arXiv',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Computer Science - AI',
  'feed_url': 'https://rss.arxiv.org/rss/cs.AI',
  'categories': ['AI', 'Research'],
  'enabled': True,
  'priority': 62,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'arxiv:cs_lg',
  'publisher_id': 'arxiv',
  'source_en': 'arXiv',
  'source_zh': 'arXiv',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Computer Science - Machine Learning',
  'feed_url': 'https://rss.arxiv.org/rss/cs.LG',
  'categories': ['AI', 'Machine Learning', 'Research'],
  'enabled': True,
  'priority': 62,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'arxiv:cs_cl',
  'publisher_id': 'arxiv',
  'source_en': 'arXiv',
  'source_zh': 'arXiv',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Computer Science - NLP',
  'feed_url': 'https://rss.arxiv.org/rss/cs.CL',
  'categories': ['AI', 'NLP', 'Research'],
  'enabled': True,
  'priority': 64,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'arxiv:cs_cv',
  'publisher_id': 'arxiv',
  'source_en': 'arXiv',
  'source_zh': 'arXiv',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Computer Science - Computer Vision',
  'feed_url': 'https://rss.arxiv.org/rss/cs.CV',
  'categories': ['AI', 'Computer Vision', 'Research'],
  'enabled': True,
  'priority': 64,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:frontpage',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Front Page',
  'feed_url': 'https://hnrss.org/frontpage',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:best',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Best',
  'feed_url': 'https://hnrss.org/best',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:ask',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Ask HN',
  'feed_url': 'https://hnrss.org/ask',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 70,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:show',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Show HN',
  'feed_url': 'https://hnrss.org/show',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 70,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:ai',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'AI Search',
  'feed_url': 'https://hnrss.org/newest?q=AI',
  'categories': ['AI', 'Technology'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:llm',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'LLM Search',
  'feed_url': 'https://hnrss.org/newest?q=LLM',
  'categories': ['AI', 'Technology'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'hackernews:openclaw',
  'publisher_id': 'hackernews',
  'source_en': 'Hacker News',
  'source_zh': 'Hacker News',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'OpenClaw Search',
  'feed_url': 'https://hnrss.org/newest?q=OpenClaw',
  'categories': ['AI', 'Technology'],
  'enabled': True,
  'priority': 75,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'simonwillison:main',
  'publisher_id': 'simonwillison',
  'source_en': "Simon Willison's Blog",
  'source_zh': 'Simon Willison',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Everything',
  'feed_url': 'https://simonwillison.net/atom/everything/',
  'categories': ['AI', 'Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'sspai:main',
  'publisher_id': 'sspai',
  'source_en': 'Sspai',
  'source_zh': '少数派',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://sspai.com/feed',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 56,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'ithome:main',
  'publisher_id': 'ithome',
  'source_en': 'IT Home',
  'source_zh': 'IT之家',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.ithome.com/rss/',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'theverge:main',
  'publisher_id': 'theverge',
  'source_en': 'The Verge',
  'source_zh': 'The Verge',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.theverge.com/rss/index.xml',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 44,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'wired:main',
  'publisher_id': 'wired',
  'source_en': 'WIRED',
  'source_zh': 'WIRED',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.wired.com/feed/rss',
  'categories': ['Technology', 'Science', 'Business'],
  'enabled': True,
  'priority': 46,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'krebsonsecurity:main',
  'publisher_id': 'krebsonsecurity',
  'source_en': 'Krebs on Security',
  'source_zh': 'Krebs on Security',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://krebsonsecurity.com/feed/',
  'categories': ['Security'],
  'enabled': True,
  'priority': 64,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'schneier:main',
  'publisher_id': 'schneier',
  'source_en': 'Schneier on Security',
  'source_zh': 'Schneier on Security',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.schneier.com/feed/',
  'categories': ['Security'],
  'enabled': True,
  'priority': 64,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'cisa:news',
  'publisher_id': 'cisa',
  'source_en': 'CISA',
  'source_zh': 'CISA',
  'language': 'en',
  'region': 'usa',
  'adapter_id': 'generic_news',
  'feed_name': 'News',
  'feed_url': 'https://www.cisa.gov/news.xml',
  'categories': ['Security'],
  'enabled': True,
  'priority': 62,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'smashingmagazine:main',
  'publisher_id': 'smashingmagazine',
  'source_en': 'Smashing Magazine',
  'source_zh': 'Smashing Magazine',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.smashingmagazine.com/feed/',
  'categories': ['Web Development', 'Design'],
  'enabled': True,
  'priority': 72,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'codrops:main',
  'publisher_id': 'codrops',
  'source_en': 'Codrops',
  'source_zh': 'Codrops',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://tympanus.net/codrops/feed/',
  'categories': ['Web Development', 'Design'],
  'enabled': True,
  'priority': 74,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'devto:main',
  'publisher_id': 'devto',
  'source_en': 'Dev.to',
  'source_zh': 'Dev.to',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://dev.to/feed',
  'categories': ['Technology', 'Development'],
  'enabled': True,
  'priority': 74,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'producthunt:main',
  'publisher_id': 'producthunt',
  'source_en': 'Product Hunt',
  'source_zh': 'Product Hunt',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.producthunt.com/feed',
  'categories': ['Technology', 'Startups'],
  'enabled': False,
  'priority': 70,
  'metadata': {'disabled_reason': 'article_pages_return_403',
               'origin': 'feeds.opml'}},
 {'id': 'rust:blog',
  'publisher_id': 'rust',
  'source_en': 'Rust Blog',
  'source_zh': 'Rust Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://blog.rust-lang.org/feed.xml',
  'categories': ['Programming'],
  'enabled': True,
  'priority': 76,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'python:blog',
  'publisher_id': 'python',
  'source_en': 'Python Blog',
  'source_zh': 'Python Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://blog.python.org/feeds/posts/default',
  'categories': ['Programming'],
  'enabled': True,
  'priority': 76,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'nodejs:blog',
  'publisher_id': 'nodejs',
  'source_en': 'Node.js Blog',
  'source_zh': 'Node.js Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://nodejs.org/en/feed/blog.xml',
  'categories': ['Programming'],
  'enabled': True,
  'priority': 76,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'swift:blog',
  'publisher_id': 'swift',
  'source_en': 'Swift Blog',
  'source_zh': 'Swift Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.swift.org/atom.xml',
  'categories': ['Programming'],
  'enabled': True,
  'priority': 78,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'kotlin:blog',
  'publisher_id': 'kotlin',
  'source_en': 'Kotlin Blog',
  'source_zh': 'Kotlin Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://blog.jetbrains.com/kotlin/feed/',
  'categories': ['Programming'],
  'enabled': True,
  'priority': 78,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'github:blog',
  'publisher_id': 'github',
  'source_en': 'GitHub Blog',
  'source_zh': 'GitHub Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://github.blog/feed/',
  'categories': ['Technology', 'Development'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'netflixtech:main',
  'publisher_id': 'netflixtech',
  'source_en': 'Netflix Tech Blog',
  'source_zh': 'Netflix Tech Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://netflixtechblog.com/feed',
  'categories': ['Engineering'],
  'enabled': True,
  'priority': 72,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'aws:blog',
  'publisher_id': 'aws',
  'source_en': 'AWS Blog',
  'source_zh': 'AWS Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://aws.amazon.com/blogs/aws/feed/',
  'categories': ['Cloud', 'Technology'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'cloudflare:blog',
  'publisher_id': 'cloudflare',
  'source_en': 'Cloudflare Blog',
  'source_zh': 'Cloudflare Blog',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://blog.cloudflare.com/rss/',
  'categories': ['Cloud', 'Security', 'Technology'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'mozilla:hacks',
  'publisher_id': 'mozilla',
  'source_en': 'Mozilla Hacks',
  'source_zh': 'Mozilla Hacks',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://hacks.mozilla.org/feed/',
  'categories': ['Web Development'],
  'enabled': True,
  'priority': 74,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'spotifyengineering:main',
  'publisher_id': 'spotifyengineering',
  'source_en': 'Spotify Engineering',
  'source_zh': 'Spotify Engineering',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://engineering.atspotify.com/feed/',
  'categories': ['Engineering'],
  'enabled': True,
  'priority': 76,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'metaengineering:main',
  'publisher_id': 'metaengineering',
  'source_en': 'Meta Engineering',
  'source_zh': 'Meta Engineering',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://engineering.fb.com/feed/',
  'categories': ['Engineering'],
  'enabled': True,
  'priority': 72,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'javascriptweekly:main',
  'publisher_id': 'javascriptweekly',
  'source_en': 'JavaScript Weekly',
  'source_zh': 'JavaScript Weekly',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://javascriptweekly.com/rss/',
  'categories': ['Programming', 'JavaScript'],
  'enabled': True,
  'priority': 76,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'thisweekinrust:main',
  'publisher_id': 'thisweekinrust',
  'source_en': 'This Week in Rust',
  'source_zh': 'This Week in Rust',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://this-week-in-rust.org/atom.xml',
  'categories': ['Programming', 'Rust'],
  'enabled': True,
  'priority': 78,
  'metadata': {'origin': 'feeds.opml'}},
 {'id': 'golangweekly:main',
  'publisher_id': 'golangweekly',
  'source_en': 'Golang Weekly',
  'source_zh': 'Golang Weekly',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'generic_news',
  'feed_name': 'Main',
  'feed_url': 'https://golangweekly.com/rss/',
  'categories': ['Programming', 'Go'],
  'enabled': True,
  'priority': 78,
  'metadata': {'origin': 'feeds.opml'}}]
RSS_SOURCES: List[RssSource] = [RssSource(**item) for item in RSS_SOURCE_DATA]
RSS_SOURCE_COUNT = len(RSS_SOURCES)

def _normalize_filters(values: Sequence[str] | None) -> set[str]:
    return {str(item).strip() for item in (values or []) if str(item).strip()}

def list_rss_sources(*, enabled_only: bool = True, publisher_ids: Sequence[str] | None = None, source_ids: Sequence[str] | None = None) -> List[RssSource]:
    publisher_filter = _normalize_filters(publisher_ids)
    source_filter = _normalize_filters(source_ids)
    items: List[RssSource] = []
    for source in RSS_SOURCES:
        if enabled_only and not source.enabled:
            continue
        if publisher_filter and source.publisher_id not in publisher_filter:
            continue
        if source_filter and source.id not in source_filter:
            continue
        items.append(source)
    return items

def list_publishers() -> List[str]:
    return sorted({source.publisher_id for source in RSS_SOURCES})

def get_rss_source(source_id: str) -> RssSource:
    for source in RSS_SOURCES:
        if source.id == source_id:
            return source
    raise KeyError(f'RSS source not found: {source_id}')
