from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Sequence

@dataclass(frozen=True, slots=True)
class RssSource:
    id: str
    publisher_id: str
    source_en: str
    source_zh: str
    feed_name: str
    feed_url: str
    adapter_id: str
    language: str = 'en'
    region: str = 'global'
    categories: List[str] = field(default_factory=list)
    enabled: bool = True
    priority: int = 50
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

RSS_SOURCE_DATA = [{'id': 'aa:default',
  'publisher_id': 'aa',
  'source_en': 'Anadolu Agency',
  'source_zh': '阿纳多卢通讯社',
  'language': 'tr',
  'region': 'turkey',
  'adapter_id': 'aa',
  'feed_name': 'Default',
  'feed_url': 'https://www.aa.com.tr/tr/rss',
  'categories': ['Default'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:top_stories',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'Top Stories',
  'feed_url': 'https://www.abc.net.au/news/feed/10719986/rss.xml',
  'categories': ['Top Stories'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:world',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'World',
  'feed_url': 'https://www.abc.net.au/news/feed/104217382/rss.xml',
  'categories': ['World'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:business',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'Business',
  'feed_url': 'https://www.abc.net.au/news/feed/104217374/rss.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'abc_au:politics',
  'publisher_id': 'abc_au',
  'source_en': 'ABC News Australia',
  'source_zh': '澳大利亚ABC新闻',
  'language': 'en',
  'region': 'australia',
  'adapter_id': 'abc',
  'feed_name': 'Politics',
  'feed_url': 'https://www.abc.net.au/news/feed/104217372/rss.xml',
  'categories': ['Politics'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'aljazeera:all',
  'publisher_id': 'aljazeera',
  'source_en': 'Al Jazeera',
  'source_zh': '半岛电视台',
  'language': 'en',
  'region': 'middle_east',
  'adapter_id': 'aljazeera',
  'feed_name': 'All',
  'feed_url': 'https://www.aljazeera.com/xml/rss/all.xml',
  'categories': ['All'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:africa',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Africa',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/africa/rss.xml',
  'categories': ['Africa'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:asia',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Asia',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/asia/rss.xml',
  'categories': ['Asia'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:europe',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Europe',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/europe/rss.xml',
  'categories': ['Europe'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:latin_america',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Latin America',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/latin_america/rss.xml',
  'categories': ['Latin America'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:middle_east',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Middle East',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/middle_east/rss.xml',
  'categories': ['Middle East'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:us_and_canada',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'US & Canada',
  'feed_url': 'https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml',
  'categories': ['US & Canada'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:england',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'England',
  'feed_url': 'https://feeds.bbci.co.uk/news/england/rss.xml',
  'categories': ['England'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:northern_ireland',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Northern Ireland',
  'feed_url': 'https://feeds.bbci.co.uk/news/northern_ireland/rss.xml',
  'categories': ['Northern Ireland'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:scotland',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Scotland',
  'feed_url': 'https://feeds.bbci.co.uk/news/scotland/rss.xml',
  'categories': ['Scotland'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'bbc:wales',
  'publisher_id': 'bbc',
  'source_en': 'BBC',
  'source_zh': 'BBC',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'bbc',
  'feed_name': 'Wales',
  'feed_url': 'https://feeds.bbci.co.uk/news/wales/rss.xml',
  'categories': ['Wales'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:world_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'World News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-world',
  'categories': ['World News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:canada_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'Canada News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-canada',
  'categories': ['Canada News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:business_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'Business News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-business',
  'categories': ['Business News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'cbc:technology_news',
  'publisher_id': 'cbc',
  'source_en': 'CBC News',
  'source_zh': '加拿大广播公司',
  'language': 'en',
  'region': 'canada',
  'adapter_id': 'cbc',
  'feed_name': 'Technology News',
  'feed_url': 'https://www.cbc.ca/webfeed/rss/rss-technology',
  'categories': ['Technology News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:时政新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '时政新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/china.xml',
  'categories': ['时政新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:国际新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '国际新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/world.xml',
  'categories': ['国际新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:财经新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '财经新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/finance.xml',
  'categories': ['财经新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:即时新闻',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '即时新闻',
  'feed_url': 'https://www.chinanews.com.cn/rss/scroll-news.xml',
  'categories': ['即时新闻'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'chinanews:要闻导读',
  'publisher_id': 'chinanews',
  'source_en': 'China News Service',
  'source_zh': '中国新闻网',
  'language': 'zh-CN',
  'region': 'china',
  'adapter_id': 'chinanews',
  'feed_name': '要闻导读',
  'feed_url': 'https://www.chinanews.com.cn/rss/importnews.xml',
  'categories': ['要闻导读'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:germany',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Germany',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-ger',
  'categories': ['Germany'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:world',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'World',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-world',
  'categories': ['World'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:europe',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Europe',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-eu',
  'categories': ['Europe'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:africa',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Africa',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-africa',
  'categories': ['Africa'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:business',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Business',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-bus',
  'categories': ['Business'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:science',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Science',
  'feed_url': 'https://rss.dw.com/xml/rss_en_science',
  'categories': ['Science'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'dw:asia',
  'publisher_id': 'dw',
  'source_en': 'Deutsche Welle',
  'source_zh': '德国之声',
  'language': 'en',
  'region': 'germany',
  'adapter_id': 'dw',
  'feed_name': 'Asia',
  'feed_url': 'https://rss.dw.com/rdf/rss-en-asia',
  'categories': ['Asia'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:最新消息',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '最新消息',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ultimas-noticias/portada',
  'categories': ['最新消息'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:观看次数最多',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '观看次数最多',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/lo-mas-visto/portada',
  'categories': ['观看次数最多'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:社会',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '社会',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/sociedad/portada',
  'categories': ['社会'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:国际',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '国际',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada',
  'categories': ['国际'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:西班牙',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '西班牙',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/espana/portada',
  'categories': ['西班牙'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:经济',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '经济',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/economia/portada',
  'categories': ['经济'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:科学',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '科学',
  'feed_url': 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada',
  'categories': ['科学'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'elpais:商业',
  'publisher_id': 'elpais',
  'source_en': 'El Pais',
  'source_zh': '国家报',
  'language': 'es',
  'region': 'spain',
  'adapter_id': 'elpais',
  'feed_name': '商业',
  'feed_url': 'https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/economia/subsection/negocios',
  'categories': ['商业'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:analysis',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Analysis',
  'feed_url': 'https://www.investing.com/rss/121899.rss',
  'categories': ['Analysis'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:market_overview',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Market Overview',
  'feed_url': 'https://www.investing.com/rss/market_overview.rss',
  'categories': ['Market Overview'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:swot_analysis_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'SWOT Analysis News',
  'feed_url': 'https://www.investing.com/rss/news_1060.rss',
  'categories': ['SWOT Analysis News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:stock_analyst_ratings',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Stock Analyst Ratings',
  'feed_url': 'https://www.investing.com/rss/news_1061.rss',
  'categories': ['Stock Analyst Ratings'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:cryptocurrency_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Cryptocurrency News',
  'feed_url': 'https://www.investing.com/rss/news_301.rss',
  'categories': ['Cryptocurrency News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:company_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Company News',
  'feed_url': 'https://www.investing.com/rss/news_356.rss',
  'categories': ['Company News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:insider_trading_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Insider Trading News',
  'feed_url': 'https://www.investing.com/rss/news_357.rss',
  'categories': ['Insider Trading News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:forex_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Forex News',
  'feed_url': 'https://www.investing.com/rss/news_1.rss',
  'categories': ['Forex News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:commodities_and_futures_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Commodities & Futures News',
  'feed_url': 'https://www.investing.com/rss/news_11.rss',
  'categories': ['Commodities & Futures News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:stock_market_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Stock Market News',
  'feed_url': 'https://www.investing.com/rss/news_25.rss',
  'categories': ['Stock Market News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:economic_indicators_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Economic Indicators News',
  'feed_url': 'https://www.investing.com/rss/news_95.rss',
  'categories': ['Economic Indicators News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'investing:economy_news',
  'publisher_id': 'investing',
  'source_en': 'Investing.com',
  'source_zh': '英为财情',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'investing',
  'feed_name': 'Economy News',
  'feed_url': 'https://www.investing.com/rss/news_14.rss',
  'categories': ['Economy News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_1',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 1',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat1.xml',
  'categories': ['Category 1'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_4',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 4',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat4.xml',
  'categories': ['Category 4'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_5',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 5',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat5.xml',
  'categories': ['Category 5'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'nhk:category_6',
  'publisher_id': 'nhk',
  'source_en': 'NHK',
  'source_zh': '日本放送协会',
  'language': 'ja',
  'region': 'japan',
  'adapter_id': 'nhk',
  'feed_name': 'Category 6',
  'feed_url': 'https://www.nhk.or.jp/rss/news/cat6.xml',
  'categories': ['Category 6'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:message',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Message',
  'feed_url': 'https://www.rfi.fr/fr/contenu/general/rss',
  'categories': ['Message'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:africa',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Africa',
  'feed_url': 'https://www.rfi.fr/afrique/rss',
  'categories': ['Africa'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:americas',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Americas',
  'feed_url': 'https://www.rfi.fr/ameriques/rss',
  'categories': ['Americas'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:asia_pacific',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Asia Pacific',
  'feed_url': 'https://www.rfi.fr/asie-pacifique/rss',
  'categories': ['Asia Pacific'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:europe',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Europe',
  'feed_url': 'https://www.rfi.fr/europe/rss',
  'categories': ['Europe'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:france',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'France',
  'feed_url': 'https://www.rfi.fr/france/rss',
  'categories': ['France'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:middle_east',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Middle East',
  'feed_url': 'https://www.rfi.fr/moyen-orient/rss',
  'categories': ['Middle East'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:economy',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Economy',
  'feed_url': 'https://www.rfi.fr/economie/rss',
  'categories': ['Economy'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'rfi:science',
  'publisher_id': 'rfi',
  'source_en': 'RFI',
  'source_zh': '法国国际广播电台',
  'language': 'fr',
  'region': 'france',
  'adapter_id': 'rfi',
  'feed_name': 'Science',
  'feed_url': 'https://www.rfi.fr/science/rss',
  'categories': ['Science'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:usa',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'USA',
  'feed_url': 'https://www.voanews.com/api/zqboml-vomx-tpeivmy',
  'categories': ['USA'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:all_about_america',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'All About America',
  'feed_url': 'https://www.voanews.com/api/zb__qtl-vomx-tpeqrtqq',
  'categories': ['All About America'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:immigration',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Immigration',
  'feed_url': 'https://www.voanews.com/api/zgvmqyl-vomx-tpe-qvqv',
  'categories': ['Immigration'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:africa',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Africa',
  'feed_url': 'https://www.voanews.com/api/z-botl-vomx-tpertmq',
  'categories': ['Africa'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:east_asia',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'East Asia',
  'feed_url': 'https://www.voanews.com/api/zobo_l-vomx-tpepvmv',
  'categories': ['East Asia'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:china_news',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'China News',
  'feed_url': 'https://www.voanews.com/api/zmjuqtl-vomx-tpey_jqq',
  'categories': ['China News'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:south_and_central_asia',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'South & Central Asia',
  'feed_url': 'https://www.voanews.com/api/z_-mqyl-vomx-tpevyvqv',
  'categories': ['South & Central Asia'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:middle_east',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Middle East',
  'feed_url': 'https://www.voanews.com/api/zrbopl-vomx-tpeovm_',
  'categories': ['Middle East'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:iran',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Iran',
  'feed_url': 'https://www.voanews.com/api/zvgmqil-vomx-tpeumvqm',
  'categories': ['Iran'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:europe',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Europe',
  'feed_url': 'https://www.voanews.com/api/zjbovl-vomx-tpebvmr',
  'categories': ['Europe'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:ukraine',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Ukraine',
  'feed_url': 'https://www.voanews.com/api/zt_rqyl-vomx-tpekboq_',
  'categories': ['Ukraine'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:americas',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Americas',
  'feed_url': 'https://www.voanews.com/api/zoripl-vomx-tpeptmm',
  'categories': ['Americas'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:technology',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Technology',
  'feed_url': 'https://www.voanews.com/api/zyritl-vomx-tpettmq',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'voa:economy',
  'publisher_id': 'voa',
  'source_en': 'VOA News',
  'source_zh': '美国之音',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'voa',
  'feed_name': 'Economy',
  'feed_url': 'https://www.voanews.com/api/zyboql-vomx-tpetvmi',
  'categories': ['Economy'],
  'enabled': True,
  'priority': 50,
  'metadata': {'origin': 'legacy_crawtasks'}},
 {'id': 'guardian:world',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'World',
  'feed_url': 'https://www.theguardian.com/world/rss',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'guardian:business',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'Business',
  'feed_url': 'https://www.theguardian.com/business/rss',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'guardian:technology',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'Technology',
  'feed_url': 'https://www.theguardian.com/technology/rss',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'guardian:environment',
  'publisher_id': 'guardian',
  'source_en': 'The Guardian',
  'source_zh': '卫报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'guardian',
  'feed_name': 'Environment',
  'feed_url': 'https://www.theguardian.com/environment/rss',
  'categories': ['Environment'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'nyt:world',
  'publisher_id': 'nyt',
  'source_en': 'The New York Times',
  'source_zh': '纽约时报',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'nyt',
  'feed_name': 'World',
  'feed_url': 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'nyt:business',
  'publisher_id': 'nyt',
  'source_en': 'The New York Times',
  'source_zh': '纽约时报',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'nyt',
  'feed_name': 'Business',
  'feed_url': 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'nyt:technology',
  'publisher_id': 'nyt',
  'source_en': 'The New York Times',
  'source_zh': '纽约时报',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'nyt',
  'feed_name': 'Technology',
  'feed_url': 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'ft:world',
  'publisher_id': 'ft',
  'source_en': 'Financial Times',
  'source_zh': '金融时报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ft',
  'feed_name': 'World',
  'feed_url': 'https://www.ft.com/world?format=rss',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'ft:companies',
  'publisher_id': 'ft',
  'source_en': 'Financial Times',
  'source_zh': '金融时报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ft',
  'feed_name': 'Companies',
  'feed_url': 'https://www.ft.com/companies?format=rss',
  'categories': ['Companies'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'ft:technology',
  'publisher_id': 'ft',
  'source_en': 'Financial Times',
  'source_zh': '金融时报',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ft',
  'feed_name': 'Technology',
  'feed_url': 'https://www.ft.com/technology?format=rss',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'npr:world',
  'publisher_id': 'npr',
  'source_en': 'NPR',
  'source_zh': '美国国家公共电台',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'npr',
  'feed_name': 'World',
  'feed_url': 'https://feeds.npr.org/1004/rss.xml',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'npr:business',
  'publisher_id': 'npr',
  'source_en': 'NPR',
  'source_zh': '美国国家公共电台',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'npr',
  'feed_name': 'Business',
  'feed_url': 'https://feeds.npr.org/1006/rss.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'npr:technology',
  'publisher_id': 'npr',
  'source_en': 'NPR',
  'source_zh': '美国国家公共电台',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'npr',
  'feed_name': 'Technology',
  'feed_url': 'https://feeds.npr.org/1019/rss.xml',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'politico:politics',
  'publisher_id': 'politico',
  'source_en': 'Politico',
  'source_zh': '政客',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'politico',
  'feed_name': 'Politics',
  'feed_url': 'https://rss.politico.com/politics-news.xml',
  'categories': ['Politics'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'techcrunch:startup_and_tech',
  'publisher_id': 'techcrunch',
  'source_en': 'TechCrunch',
  'source_zh': 'TechCrunch',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'techcrunch',
  'feed_name': 'Main Feed',
  'feed_url': 'https://techcrunch.com/feed/',
  'categories': ['Technology', 'Startups'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'cnbc:world',
  'publisher_id': 'cnbc',
  'source_en': 'CNBC',
  'source_zh': '美国消费者新闻与商业频道',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'cnbc',
  'feed_name': 'World',
  'feed_url': 'https://www.cnbc.com/id/100727362/device/rss/rss.html',
  'categories': ['World'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'cnbc:business',
  'publisher_id': 'cnbc',
  'source_en': 'CNBC',
  'source_zh': '美国消费者新闻与商业频道',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'cnbc',
  'feed_name': 'Business',
  'feed_url': 'https://www.cnbc.com/id/10001147/device/rss/rss.html',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'marketwatch:topstories',
  'publisher_id': 'marketwatch',
  'source_en': 'MarketWatch',
  'source_zh': '道琼斯市场观察',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'marketwatch',
  'feed_name': 'Top Stories',
  'feed_url': 'https://feeds.content.dowjones.io/public/rss/mw_topstories',
  'categories': ['Markets', 'Top Stories'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'marketwatch:marketpulse',
  'publisher_id': 'marketwatch',
  'source_en': 'MarketWatch',
  'source_zh': '道琼斯市场观察',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'marketwatch',
  'feed_name': 'Market Pulse',
  'feed_url': 'https://feeds.content.dowjones.io/public/rss/mw_marketpulse',
  'categories': ['Markets'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'marketwatch:realtime',
  'publisher_id': 'marketwatch',
  'source_en': 'MarketWatch',
  'source_zh': '道琼斯市场观察',
  'language': 'en',
  'region': 'united_states',
  'adapter_id': 'marketwatch',
  'feed_name': 'Realtime Headlines',
  'feed_url': 'https://feeds.content.dowjones.io/public/rss/mw_realtimeheadlines',
  'categories': ['Markets', 'Realtime'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'economist:international',
  'publisher_id': 'economist',
  'source_en': 'The Economist',
  'source_zh': '经济学人',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'economist',
  'feed_name': 'International',
  'feed_url': 'https://www.economist.com/international/rss.xml',
  'categories': ['International'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'economist:business',
  'publisher_id': 'economist',
  'source_en': 'The Economist',
  'source_zh': '经济学人',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'economist',
  'feed_name': 'Business',
  'feed_url': 'https://www.economist.com/business/rss.xml',
  'categories': ['Business'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'economist:finance',
  'publisher_id': 'economist',
  'source_en': 'The Economist',
  'source_zh': '经济学人',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'economist',
  'feed_name': 'Finance and Economics',
  'feed_url': 'https://www.economist.com/finance-and-economics/rss.xml',
  'categories': ['Finance', 'Economics'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_worldmonitor_style'}},
 {'id': 'un_news:all',
  'publisher_id': 'un_news',
  'source_en': 'UN News',
  'source_zh': '联合国新闻',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'un_news',
  'feed_name': 'All News',
  'feed_url': 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
  'categories': ['World', 'Policy'],
  'enabled': True,
  'priority': 62,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'mit_tech_review:main',
  'publisher_id': 'mit_tech_review',
  'source_en': 'MIT Technology Review',
  'source_zh': '麻省理工科技评论',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'mit_tech_review',
  'feed_name': 'Main',
  'feed_url': 'https://www.technologyreview.com/feed/',
  'categories': ['Technology', 'AI'],
  'enabled': True,
  'priority': 61,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'ars:main',
  'publisher_id': 'ars',
  'source_en': 'Ars Technica',
  'source_zh': 'Ars Technica',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'ars',
  'feed_name': 'Main',
  'feed_url': 'https://feeds.arstechnica.com/arstechnica/index',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 61,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'register:headlines',
  'publisher_id': 'register',
  'source_en': 'The Register',
  'source_zh': 'The Register',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'register',
  'feed_name': 'Headlines',
  'feed_url': 'https://www.theregister.com/headlines.atom',
  'categories': ['Technology'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'nature:main',
  'publisher_id': 'nature',
  'source_en': 'Nature',
  'source_zh': 'Nature',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'nature',
  'feed_name': 'Main',
  'feed_url': 'https://www.nature.com/nature.rss',
  'categories': ['Science'],
  'enabled': True,
  'priority': 60,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'nasa:breaking',
  'publisher_id': 'nasa',
  'source_en': 'NASA',
  'source_zh': '美国国家航空航天局',
  'language': 'en',
  'region': 'us',
  'adapter_id': 'nasa',
  'feed_name': 'Breaking News',
  'feed_url': 'https://www.nasa.gov/rss/dyn/breaking_news.rss',
  'categories': ['Science', 'Space'],
  'enabled': True,
  'priority': 59,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'stat_news:main',
  'publisher_id': 'stat_news',
  'source_en': 'STAT',
  'source_zh': 'STAT',
  'language': 'en',
  'region': 'us',
  'adapter_id': 'stat_news',
  'feed_name': 'Main',
  'feed_url': 'https://www.statnews.com/feed/',
  'categories': ['Health', 'Science'],
  'enabled': True,
  'priority': 59,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'foreign_policy:main',
  'publisher_id': 'foreign_policy',
  'source_en': 'Foreign Policy',
  'source_zh': '外交政策',
  'language': 'en',
  'region': 'global',
  'adapter_id': 'foreign_policy',
  'feed_name': 'Main',
  'feed_url': 'https://foreignpolicy.com/feed/',
  'categories': ['World', 'Politics'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}},
 {'id': 'euronews:news',
  'publisher_id': 'euronews',
  'source_en': 'Euronews',
  'source_zh': '欧洲新闻台',
  'language': 'en',
  'region': 'europe',
  'adapter_id': 'euronews',
  'feed_name': 'News',
  'feed_url': 'https://www.euronews.com/rss?level=theme&name=news',
  'categories': ['World', 'Europe'],
  'enabled': True,
  'priority': 58,
  'metadata': {'origin': 'supplemental_verified_2026_03_26'}}]

RSS_SOURCES: List[RssSource] = [RssSource(**item) for item in RSS_SOURCE_DATA]
RSS_SOURCE_COUNT = len(RSS_SOURCES)

def _normalize_filters(values: Sequence[str] | None) -> set[str]:
    return {str(item).strip() for item in (values or []) if str(item).strip()}

def list_rss_sources(*, enabled_only: bool = True, publisher_ids: Sequence[str] | None = None, source_ids: Sequence[str] | None = None) -> List[RssSource]:
    publisher_filter = _normalize_filters(publisher_ids)
    source_filter = _normalize_filters(source_ids)
    items: List[RssSource] = []
    for source in RSS_SOURCES:
        if enabled_only and not source.enabled:
            continue
        if publisher_filter and source.publisher_id not in publisher_filter:
            continue
        if source_filter and source.id not in source_filter:
            continue
        items.append(source)
    return items

def list_publishers() -> List[str]:
    return sorted({source.publisher_id for source in RSS_SOURCES})

def get_rss_source(source_id: str) -> RssSource:
    for source in RSS_SOURCES:
        if source.id == source_id:
            return source
    raise KeyError(f'RSS source not found: {source_id}')

